### ISSUE TITLE
How to read whole line?

### ISSUE THREAD

**Issue by WeetHet** [byorgey/comprog-hs#1]
In some problems you are given a number of lines with different lengths, so words is definitely wrong to use here. Instead we can use lines, but it makes all functions useless, because you have to parse lines by-hand. Is there any workaround to solve this?

**Comment by byorgey** [comment]
Typically, what I do in this case is use `runScannerWith lines`, and then perhaps use a nested invocation of `runScanner` to parse individual lines.  For example, here is my parsing code for https://open.kattis.com/problems/overthehill1 :

```
main = C.interact $ runScannerWith C.lines tc >>> solve

newtype N37 = N37 { unN37 :: Int } deriving (Eq, Ord, Show)
instance Num N37 where
  fromInteger n = N37 (fromInteger n `mod` 37)
  (N37 a) + (N37 b) = N37 ((a + b) `mod` 37)
  (N37 a) - (N37 b) = N37 ((a - b) `mod` 37)
  (N37 a) * (N37 b) = N37 ((a * b) `mod` 37)

data TC = TC { n :: Int, m :: Matrix N37, plaintext :: ByteString }
  deriving (Eq, Show)

tc :: Scanner TC
tc = do
  n <- int
  m <- fromList . map (runScanner (n >< (N37 <$> int))) <$> (n >< str)
  plaintext <- str
  return TC{..}
```

**Comment by WeetHet** [comment]
Thank you
